---
# If OS family is RedHat then
- name: install or update yum utils
  yum:
    name: yum-utils
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: install or update EPEL repository
  yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: install or update python
  yum:
    name: python3
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: install or update vim
  yum:
    name: vim
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: remove nano
  yum:
    name: nano
    state: absent
  when: ansible_facts['os_family'] == 'RedHat'

- name: install or update curl
  yum:
    name: curl
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: install or update htop
  yum:
    name: htop
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: update sshd
  yum:
    name: openssh-server
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

# If OS family is Debian then
- name: install or update python
  apt:
    name: python3
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: install or update vim
  apt:
    name: vim
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: remove nano
  apt:
    name: nano
    state: absent
  when: ansible_facts['os_family'] == 'Debian'

- name: install or update curl
  apt:
    name: curl
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: install or update htop
  apt:
    name: htop
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: update sshd
  apt:
    name: openssh-server
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

# General tasks for any OS family

- name: configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart sshd