---
# If OS family is RedHat then
- name: '[rhel] install or update basic packages'
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - yum-utils
    - epel-release
    - python3
    - vim
    - curl
    - htop
    - wget
    - openssh-server
  when: ansible_facts['os_family'] == 'RedHat'

- name: remove unnecessary packages
  yum:
    name: "{{item}}"
    state: absent
  loop:
    - nano
  when: ansible_facts['os_family'] == 'RedHat'

# If OS family is Debian then
- name: '[deb] install or update basic packages'
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - python3
    - vim
    - curl
    - htop
    - wget
    - openssh-server
  when: ansible_facts['os_family'] == 'Debian'

- name: remove unnecessary packages
  apt:
    name: "{{item}}"
    state: absent
  loop:
    - nano
  when: ansible_facts['os_family'] == 'Debian'

# General tasks for any OS family
 - name: configure sshd
   template:
     src: sshd_config.j2
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: '0600'
   notify: restart sshd