---
- name: check current OS version
  command: uname -mrs
  register: system_info
- name: display kernel version
  debug:
    var: system_info.stdout_lines

- name: update and upgrade debian systems
  apt:
    update_cache: yes
    upgrade: dist

- name: reboot if kernel/libs require to
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting to update kernel'
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true

- name: wait for system to reboot
  wait_for_connection:
    delay: 60
    timeout: 300

- name: verify new update
  command: uname -mrs
  register: system_info
- name: display kernel version
  debug:
    var: system_info.stdout_lines