---
- name: local ssh keys setup
  hosts: localhost
  vars_prompt:
    - name: ssh_setup
      prompt: "Do you want to setup passwordless ssh connections? (yes/no)"
      default: "no"
      private: "no"
  pre_tasks:
    - pause:
        prompt: "Which key type you want to use? (rsa, dsa, ecdsa, ed25519)"
      register: keytype
      when: ssh_setup == "yes"
    - pause:
        prompt: "What you want to name your ssh key file?"
      register: ssh_key_filename
      when: ssh_setup == "yes"
    - set_fact:
        ssh_setup: "{{ssh_setup}}"
        ssh_key_filename: "{{ssh_key_filename.user_input}}"
        keytype: "{{keytype.user_input}}"
      when: ssh_setup is defined and ssh_setup == 'yes'

  roles:
    - role: ssh_key
      when: ssh_setup == true
################################################################
- name: setup passwordless SSH
  hosts: all,!localhost
  vars:
    ssh_setup: "{{hostvars['localhost']['ssh_setup']}}"
    ssh_key_filename: "{{hostvars['localhost']['ssh_key_filename']}}"
  tasks:
    - name: upload public key
      authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{ lookup('file', '~/.ssh/{{ssh_key_filename}}.pub') }}"
      when: ssh_setup is defined and ssh_setup is true
################################################################
- name: setup new machine
  vars_prompt:
    - name: install_baseline
      prompt: "Do you want to perform basic system setup? (yes/no)"
      default: "no"
      private: "no"

    - name: run_updates
      prompt: "Do you want to run system updates? (yes/no)"
      default: "no"
      private: "no"

    - name: install_docker
      prompt: "Do you want to install Docker? (yes/no)"
      default: "no"
      private: "no"

    - name: install_git
      prompt: "Do you want to install Git? (yes/no)"
      default: "no"
      private: "no"

    - name: install_zabbix_agent
      prompt: "Do you want to install Zabbix agent? (yes/no)"
      default: "no"
      private: "no"
  hosts: all
  become: true
  become_method: sudo
  remote_user: control
  roles:
    - role: baseline
      when: install_baseline == "yes"
    - role: docker
      when: install_docker == "yes"
    - role: git
      when: install_git == "yes"
    - role: update
      when: run_updates == "yes"
    - role: zabbix-agent
      when: install_zabbix_agent == "yes"