---
- name: update existing operating systems
  hosts: all
  become: true
  become_method: sudo
  roles:
    - debian-update
      when: ansible_facts['os_family'] == 'Debian'
    - redhat-update
      when: ansible_facts['os_family'] == 'RedHat'
