---
# - pause:
#     prompt: "Which key type you want to use? (rsa, dsa, ecdsa, ed25519)"
#     echo: yes
#     default: rsa

# - pause:
#     prompt: "What you want to name your ssh key file?"
#     echo: yes
#     default: id_rsa
    
- name: check that the ssh local directory exists
  stat:
    path: "~/.ssh"
  register: ssh_local_dir

- name: create ssh local directory if it doesn't exist
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700
  when: ssh_local_dir is defined and ssh_local_dir.stat.exists != true

- name: check that the key exists
  stat:
    path: "~/.ssh/{{ssh_key_filename}}"
  register: ssh_key_file
  with_items:
    - "{{ssh_key_filename}}"
    - "{{ssh_key_filename}}.pub"

- name: generate keys if don't exist
  shell: "ssh-keygen -t {{keytype}} -f ~/.ssh/{{ssh_key_filename}} -C ''"
  when: not ssh_key_file.results[0].stat.exists and not ssh_key_file.results[1].stat.exists